title: "INDEN Laboratory | Building Materials and Construction"
description: "Building Materials and Construction Laboratory, Kokushikan University"
url: "https://indenlab.github.io"
baseurl: ""
markdown: kramdown
theme: null
plugins: []
exclude:
  - Gemfile
  - Gemfile.lock
